#!/usr/bin/env bash
# simple_content_analyzer.sh
# Simple content quality analyzer for markdown files

set -e

PROJECT_ROOT="/Users/steven/tehSiTes"
ANALYSIS_DIR="$PROJECT_ROOT/content_analysis/$(date +%Y%m%d_%H%M%S)"

# Create analysis directory
mkdir -p "$ANALYSIS_DIR"

echo "Starting Simple Content Quality Analysis..."

# Initialize CSV file
echo "File,Project,Word Count,Headers,Grade" > "$ANALYSIS_DIR/quality_summary.csv"

# Analyze markdown files
find "$PROJECT_ROOT" -name "*.md" -type f | head -20 | while read -r file; do
    if [[ -f "$file" ]]; then
        echo "Analyzing: $file"
        
        # Basic analysis
        word_count=$(wc -w < "$file" 2>/dev/null || echo "0")
        header_count=$(grep -c "^#" "$file" 2>/dev/null || echo "0")
        
        # Simple grading
        if [[ $word_count -gt 1000 && $header_count -gt 3 ]]; then
            grade="A+"
        elif [[ $word_count -gt 500 && $header_count -gt 2 ]]; then
            grade="A"
        elif [[ $word_count -gt 200 && $header_count -gt 1 ]]; then
            grade="B"
        else
            grade="C"
        fi
        
        # Extract project name from path
        project_name=$(echo "$file" | sed 's|.*/||' | sed 's|\.md||')
        
        # Add to CSV
        echo "$file,$project_name,$word_count,$header_count,$grade" >> "$ANALYSIS_DIR/quality_summary.csv"
        
        echo "  - Word count: $word_count"
        echo "  - Headers: $header_count"
        echo "  - Grade: $grade"
    fi
done

# Generate summary report
cat > "$ANALYSIS_DIR/simple_summary_report.md" << EOF
# Simple Content Quality Analysis Summary

**Analysis Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Files Analyzed:** $(wc -l < "$ANALYSIS_DIR/quality_summary.csv" 2>/dev/null || echo "0")

## Summary

This analysis provides a basic overview of content quality across your markdown files.

### Grade Distribution
- A+ (1000+ words, 4+ headers): $(grep -c "A+" "$ANALYSIS_DIR/quality_summary.csv" 2>/dev/null || echo "0") files
- A (500+ words, 3+ headers): $(grep -c "A," "$ANALYSIS_DIR/quality_summary.csv" 2>/dev/null || echo "0") files
- B (200+ words, 2+ headers): $(grep -c "B," "$ANALYSIS_DIR/quality_summary.csv" 2>/dev/null || echo "0") files
- C (less than 200 words or 1 header): $(grep -c "C," "$ANALYSIS_DIR/quality_summary.csv" 2>/dev/null || echo "0") files

## Recommendations

1. **For A+ grades:** Maintain current quality standards
2. **For A grades:** Add more detailed content and headers
3. **For B grades:** Expand content and improve structure
4. **For C grades:** Significant content expansion needed

## Next Steps

1. Review individual file analysis in the CSV file
2. Focus on improving lower-grade files
3. Maintain quality standards for high-grade files
4. Consider running the full professional format automation

---

*Generated by Simple Content Analyzer on $(date '+%Y-%m-%d %H:%M:%S')*
EOF

echo "Analysis completed!"
echo "Results saved to: $ANALYSIS_DIR"
echo "Summary report: $ANALYSIS_DIR/simple_summary_report.md"
echo "CSV data: $ANALYSIS_DIR/quality_summary.csv"
