
# Function to generate CSV and HTML reports from Noi data
generate_reports() {
    local output_dir="/Users/steven/MySites/noi-site"
    local csv_file="$output_dir/noi_data_report.csv"
    local html_file="$output_dir/index.html"
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")

    # Ensure output directory exists
    mkdir -p "$output_dir"

    # Define the Noi partitions directory
    local PARTITIONS_DIR="$HOME/Library/Application Support/Noi/Partitions/noi_main/IndexedDB"
    local MAIN_DB_DIR="$HOME/Library/Application Support/Noi/noi_user/database"

    # CSV Header
    echo "Service,Size,LastModified,RecentActivity" > "$csv_file"

    # Initialize HTML file with the requested style
    cat <<EOF > "$html_file"
<!DOCTYPE html>
<html lang="en" class="gptj">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Noi Data Dashboard</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body class="home">
    <div class="hero">
        <div class="terminal-prefix">System Status</div>
        <h1><span class="brand-line">Noi</span><span class="junkie">Data Dashboard</span></h1>
        <p class="hero-sub">Automated inventory of AI service data partitions. Last updated: $timestamp</p>
    </div>
    
    <div class="theme-section">
        <div class="section-header">
            <h2 class="section-title">Service Inventory</h2>
        </div>
        <div class="repo-grid">
EOF

    # Array of AI services
    local services=(
      "https_chatgpt.com_0.indexeddb.leveldb:ChatGPT"
      "https_claude.ai_0.indexeddb.leveldb:Claude" 
      "https_grok.com_0.indexeddb.leveldb:Grok"
      "https_z.ai_0.indexeddb.leveldb:Z.ai"
      "https_www.perplexity.ai_0.indexeddb.leveldb:Perplexity"
      "https_chat.deepseek.com_0.indexeddb.leveldb:DeepSeek"
      "https_chat.qwen.ai_0.indexeddb.leveldb:Qwen"
    )

    # Process services
    for service_entry in "${services[@]}"; do
        local dir="${service_entry%%:*}"
        local name="${service_entry##*:}"
        
        if [ -d "$PARTITIONS_DIR/$dir" ]; then
            local size=$(du -sh "$PARTITIONS_DIR/$dir" | cut -f1)
            local mod_time=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "$PARTITIONS_DIR/$dir")
            local recent_file=$(find "$PARTITIONS_DIR/$dir" -type f -exec stat -f "%m:%N" {} \; | sort -nr | head -1 | cut -d: -f2-)
            local recent_mod_time="N/A"
            if [ ! -z "$recent_file" ]; then
                recent_mod_time=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "$recent_file")
            fi

            # Add to CSV
            echo "$name,$size,$mod_time,$recent_mod_time" >> "$csv_file"

            # Add to HTML
            cat <<EOF >> "$html_file"
            <a href="#" class="repo-card ai">
                <div class="card-name">$name</div>
                <div class="card-desc">Size: $size<br>Last Mod: $mod_time</div>
                <div class="card-meta">Activity: $recent_mod_time</div>
            </a>
EOF
        fi
    done

    # Finish HTML
    cat <<EOF >> "$html_file"
        </div>
    </div>
    <div class="footer"><p class="footer-text">Generated by Noi Data Checker CLI</p></div>
</body>
</html>
EOF

    echo "✅ Reports generated in $output_dir"
}

# Run the generation
generate_reports
