#!/usr/bin/env bash
# Organize Carbon-generated images and reports into a stable folder structure.

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

ROOT_DIR="${1:-${CARBON_IMAGE_DIR:-/Users/steven/Pictures/carbon-images}}"
ORGANIZED_DIR="$ROOT_DIR/organized"

move_matches() {
    local destination=$1
    shift

    mkdir -p "$destination"

    local moved=0
    local pattern file
    shopt -s nullglob
    for pattern in "$@"; do
        for file in $pattern; do
            if [ -e "$file" ]; then
                mv -- "$file" "$destination/"
                moved=$((moved + 1))
            fi
        done
    done
    shopt -u nullglob

    if [ "$moved" -eq 0 ]; then
        echo "No files matched for $destination"
    fi
}

count_files() {
    local directory=$1
    local extension=$2

    if [ ! -d "$directory" ]; then
        echo 0
        return
    fi

    find "$directory" -maxdepth 1 -type f -name "$extension" | wc -l | tr -d ' '
}

echo -e "${CYAN}Carbon Images Cleanup Script${NC}"
echo "=================================="

if [ ! -d "$ROOT_DIR" ]; then
    echo "Image directory not found: $ROOT_DIR"
    exit 1
fi

cd "$ROOT_DIR"

echo -e "${BLUE}Creating organized directory structure...${NC}"
mkdir -p "$ORGANIZED_DIR"/{original_images,optimized_images,webp_images,scripts,reports,analysis}

echo -e "${YELLOW}Moving original PNG images...${NC}"
move_matches "$ORGANIZED_DIR/original_images" ./*.png

echo -e "${YELLOW}Moving optimized images...${NC}"
if [ -d optimized ]; then
    move_matches "$ORGANIZED_DIR/optimized_images" optimized/*.png
    rmdir optimized 2>/dev/null || true
fi

echo -e "${YELLOW}Moving WebP images...${NC}"
if [ -d webp ]; then
    move_matches "$ORGANIZED_DIR/webp_images" webp/*.webp
    rmdir webp 2>/dev/null || true
fi

echo -e "${YELLOW}Moving scripts...${NC}"
move_matches "$ORGANIZED_DIR/scripts" ./*.sh ./*.py

echo -e "${YELLOW}Moving reports and analysis...${NC}"
if [ -d reports ]; then
    move_matches "$ORGANIZED_DIR/reports" reports/*
    rmdir reports 2>/dev/null || true
fi

if [ -d analysis ]; then
    move_matches "$ORGANIZED_DIR/analysis" analysis/*
    rmdir analysis 2>/dev/null || true
fi

echo -e "${YELLOW}Moving generated helper directories...${NC}"
for dir in regenerated split statistical_carbon statistical_analysis_test; do
    if [ -d "$dir" ]; then
        mv -- "$dir" "$ORGANIZED_DIR/"
    fi
done

echo -e "${YELLOW}Moving markdown documentation...${NC}"
move_matches "$ORGANIZED_DIR/reports" ./*.md

rm -f ./.DS_Store

cat > "$ORGANIZED_DIR/README.md" <<'EOF'
# Carbon Images - Organized Structure

This directory contains Carbon-generated code images organized by type and purpose.

## Directory Structure

- `original_images/`: original PNG files generated by Carbon
- `optimized_images/`: PNG files optimized for smaller file sizes
- `webp_images/`: WebP files for web publishing
- `scripts/`: automation and optimization scripts
- `reports/`: analysis reports and documentation
- `analysis/`: raw analysis data and statistics

## Usage

- Use `webp_images/` for web pages when WebP is supported.
- Use `optimized_images/` for general publishing.
- Use `original_images/` for archive and print workflows.
EOF

echo -e "${GREEN}Cleanup summary${NC}"
echo "Original images: $(count_files "$ORGANIZED_DIR/original_images" '*.png')"
echo "Optimized images: $(count_files "$ORGANIZED_DIR/optimized_images" '*.png')"
echo "WebP images: $(count_files "$ORGANIZED_DIR/webp_images" '*.webp')"
echo "Scripts: $(count_files "$ORGANIZED_DIR/scripts" '*.sh') shell, $(count_files "$ORGANIZED_DIR/scripts" '*.py') python"
echo "Reports: $(count_files "$ORGANIZED_DIR/reports" '*.md')"
echo "Total organized: $(du -sh "$ORGANIZED_DIR" 2>/dev/null | awk '{print $1}' || echo '0B')"
echo -e "${CYAN}Organized folder: $ORGANIZED_DIR${NC}"
