#!/usr/bin/env bash

# Exit on error, undefined variables, and pipe failures
set -euo pipefail

# Configure AI Tools with ~/.env.d/ API Keys

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🔧 Configuring AI Tools with ~/.env.d/ Keys${NC}"
echo ""

# Load API keys from ~/.env.d/
if [ -f ~/.env.d/llm-apis.env ]; then
    set -o allexport
    source ~/.env.d/llm-apis.env 2>/dev/null || true
    set +o allexport
    echo "✓ Loaded API keys from ~/.env.d/llm-apis.env"
else
    echo -e "${YELLOW}⚠ ~/.env.d/llm-apis.env not found${NC}"
fi

# 1. Configure aider
echo -e "${GREEN}📝 Configuring aider...${NC}"
cat > ~/.aider.conf.yml <<EOF
# Aider Configuration
# Auto-generated by setup_ai_tools_config.sh

# Default model
model: gpt-4o-mini

# API keys (loaded from environment)
# OPENAI_API_KEY and ANTHROPIC_API_KEY should be set in environment

# Editor
editor: vim

# Git
auto-commits: true
dirty-commits: true

# Display
dark-mode: true
pretty: true
stream: true

# Code
map-tokens: 1024
EOF

echo "✓ Created ~/.aider.conf.yml"

# 2. Configure llm (Simon Willison)
echo -e "${GREEN}🤖 Configuring llm...${NC}"

# Set OpenAI key
if [ -n "$OPENAI_API_KEY" ]; then
    echo "$OPENAI_API_KEY" | llm keys set openai 2>/dev/null
    echo "✓ Set OpenAI key for llm"
fi

# Set Anthropic key
if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "$ANTHROPIC_API_KEY" | llm keys set anthropic 2>/dev/null
    echo "✓ Set Anthropic key for llm"
fi

# Set Gemini key
if [ -n "$GEMINI_API_KEY" ]; then
    echo "$GEMINI_API_KEY" | llm keys set gemini 2>/dev/null
    echo "✓ Set Gemini key for llm"
fi

# Install useful llm plugins
echo "Installing llm plugins..."
llm install llm-claude-3 2>/dev/null || true
llm install llm-gemini 2>/dev/null || true
echo "✓ Installed llm plugins"

# 3. Configure fabric
echo -e "${GREEN}🧵 Configuring fabric...${NC}"

# Fabric expects config in ~/.config/fabric/
mkdir -p ~/.config/fabric

cat > ~/.config/fabric/.env <<EOF
# Fabric Configuration
# Auto-generated by setup_ai_tools_config.sh

# OpenAI
OPENAI_API_KEY=$OPENAI_API_KEY

# Anthropic (if fabric supports it in future)
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY

# Default model
DEFAULT_MODEL=gpt-4o-mini
EOF

echo "✓ Created ~/.config/fabric/.env"

# Set up fabric patterns (first-time setup)
if [ ! -d ~/.config/fabric/patterns ]; then
    echo "Setting up fabric patterns..."
    fabric --setup 2>/dev/null || echo "⚠ Fabric setup skipped (run 'fabric --setup' manually)"
fi

# 4. Configure gptme
echo -e "${GREEN}💬 Configuring gptme...${NC}"

# gptme reads from environment, but we can create a config
mkdir -p ~/.config/gptme

cat > ~/.config/gptme/config.toml <<EOF
# gptme Configuration
# Auto-generated by setup_ai_tools_config.sh

[openai]
model = "gpt-4o-mini"

[anthropic]
model = "claude-sonnet-4"

[general]
provider = "openai"
EOF

echo "✓ Created ~/.config/gptme/config.toml"

# 5. Add to shell profile for persistent environment variables
echo -e "${GREEN}🔐 Adding API keys to shell profile...${NC}"

# Add to .zshrc if not already there
if ! grep -q "source ~/.env.d/loader.sh llm-apis" ~/.zshrc 2>/dev/null; then
    echo "" >> ~/.zshrc
    echo "# Load LLM API keys for AI tools (aider, gptme, llm, fabric)" >> ~/.zshrc
    echo "source ~/.env.d/loader.sh llm-apis 2>/dev/null || true" >> ~/.zshrc
    echo "✓ Added to ~/.zshrc"
else
    echo "✓ Already in ~/.zshrc"
fi

echo ""
echo -e "${BLUE}✅ Configuration Complete!${NC}"
echo ""
echo "Available commands:"
echo "  aider              - AI pair programming"
echo "  gptme              - ChatGPT-like CLI"
echo "  llm 'prompt'       - Universal LLM CLI"
echo "  fabric             - AI prompts for common tasks"
echo "  rga 'pattern' file - Search PDFs/docs"
echo ""
echo "Usage examples:"
echo "  aider file.py                    # Edit with AI"
echo "  gptme chat                       # Start chat"
echo "  llm 'explain this code'          # Quick LLM query"
echo "  fabric --pattern summarize < doc.txt"
echo "  rga 'search term' document.pdf"
echo ""
